#!/usr/bin/env node
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const readJSON=async rel=>JSON.parse(await fs.readFile(path.join(root,rel),'utf8'));

function glbJSON(buffer){
  if(buffer.length<20||buffer.readUInt32LE(0)!==0x46546c67)throw new Error('Not a GLB 2.0 file');
  if(buffer.readUInt32LE(4)!==2)throw new Error(`Unsupported GLB version ${buffer.readUInt32LE(4)}`);
  let off=12,json=null;
  while(off+8<=buffer.length){const len=buffer.readUInt32LE(off),type=buffer.readUInt32LE(off+4);off+=8;if(type===0x4e4f534a)json=JSON.parse(buffer.subarray(off,off+len).toString('utf8').replace(/\0+$/,''));off+=len;}
  if(!json)throw new Error('GLB missing JSON chunk');return json;
}
const I=()=>[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];
function mul(a,b){const o=new Array(16).fill(0);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o;}
function trs(n){if(n.matrix?.length===16)return [...n.matrix];const t=n.translation||[0,0,0],q=n.rotation||[0,0,0,1],s=n.scale||[1,1,1],x=q[0],y=q[1],z=q[2],w=q[3],x2=x+x,y2=y+y,z2=z+z,xx=x*x2,xy=x*y2,xz=x*z2,yy=y*y2,yz=y*z2,zz=z*z2,wx=w*x2,wy=w*y2,wz=w*z2;return [(1-(yy+zz))*s[0],(xy+wz)*s[0],(xz-wy)*s[0],0,(xy-wz)*s[1],(1-(xx+zz))*s[1],(yz+wx)*s[1],0,(xz+wy)*s[2],(yz-wx)*s[2],(1-(xx+yy))*s[2],0,t[0],t[1],t[2],1];}
function point(m,p){return [m[0]*p[0]+m[4]*p[1]+m[8]*p[2]+m[12],m[1]*p[0]+m[5]*p[1]+m[9]*p[2]+m[13],m[2]*p[0]+m[6]*p[1]+m[10]*p[2]+m[14]];}
function boundsOf(g){
  const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];let found=false;
  const roots=g.scenes?.[g.scene??0]?.nodes??g.nodes?.map((_,i)=>i).filter(i=>!g.nodes.some(n=>(n.children||[]).includes(i)))??[];
  const visit=(i,parent)=>{const n=g.nodes?.[i]||{},world=mul(parent,trs(n));if(n.mesh!=null){for(const prim of g.meshes?.[n.mesh]?.primitives||[]){const acc=g.accessors?.[prim.attributes?.POSITION];if(!acc?.min||!acc?.max)continue;for(const x of [acc.min[0],acc.max[0]])for(const y of [acc.min[1],acc.max[1]])for(const z of [acc.min[2],acc.max[2]]){const p=point(world,[x,y,z]);for(let k=0;k<3;k++){min[k]=Math.min(min[k],p[k]);max[k]=Math.max(max[k],p[k]);}found=true;}}}for(const child of n.children||[])visit(child,world);};
  for(const r of roots)visit(r,I());if(!found)return null;return {min,max,size:[max[0]-min[0],max[1]-min[1],max[2]-min[2]]};
}
const uniq=a=>[...new Set(a)].sort();
const pivotPattern=/(wheel|turret|gun|muzzle|socket|door|gate|fan|rotor|radar|arm|collector|hopper|intake|feeder|conveyor|steer|sprocket|idler|roller)/i;
function audit(assetId,info,g){
  const nodes=(g.nodes||[]).map((n,i)=>n.name||`node_${i}`),clips=(g.animations||[]).map((a,i)=>a.name||`animation_${i}`),materials=(g.materials||[]).map((m,i)=>m.name||`material_${i}`),meshes=(g.meshes||[]).map((m,i)=>m.name||`mesh_${i}`),pivots=nodes.filter(n=>pivotPattern.test(n)),bounds=boundsOf(g);let suggestedGeometry=null;if(bounds){const [x,y,z]=bounds.size,long=Math.max(x,z),wide=Math.min(x,z);suggestedGeometry={shape:'BOX',majorRadius:+(long/2).toFixed(3),minorRadius:+(wide/2).toFixed(3),height:+y.toFixed(3),note:'Visual-bounds suggestion only; gameplay Geometry must be authored/verified separately.'};}
  return {id:assetId,kind:info.kind,path:info.path,status:info.status||'production',bounds,animations:clips,nodes:uniq(nodes),pivotHints:uniq(pivots),materials:uniq(materials),meshes:uniq(meshes),suggestedGeometry};
}
async function main(){
  const registry=await readJSON('data/registry.json'),packs=[];for(const rel of registry.contentPacks||[])packs.push(await readJSON(rel));const catalogPaths=[...new Set([...(registry.assetCatalogs?.length?registry.assetCatalogs:['data/asset-catalog.json']),...packs.flatMap(p=>p.assetCatalogs||[])])],entries=[];
  for(const rel of catalogPaths){const cat=await readJSON(rel);for(const [id,info] of Object.entries(cat.assets||{}))entries.push([id,info]);}
  entries.sort((a,b)=>a[0].localeCompare(b[0]));const assets=[];
  for(const [id,info] of entries){const buf=await fs.readFile(path.join(root,info.path));assets.push(audit(id,info,glbJSON(buf)));}
  const report={formatVersion:1,generatedBy:'tools/audit-assets.mjs',assetCount:assets.length,assets};
  await fs.mkdir(path.join(root,'reports'),{recursive:true});await fs.writeFile(path.join(root,'reports/asset-audit.json'),JSON.stringify(report,null,2)+'\n');
  const lines=['# ForgeRTS Asset Ingestion Audit','','Generated by `tools/audit-assets.mjs`. Bounds and Geometry suggestions describe visual assets only; authoritative gameplay Geometry/Footprints remain definition data.','',`Assets audited: **${assets.length}**`,'','| Asset | Kind | Visual size X×Y×Z | Clips | Pivot hints |','|---|---|---:|---|---|'];
  for(const a of assets){const size=a.bounds?.size?.map(v=>v.toFixed(2)).join(' × ')||'n/a';lines.push(`| \`${a.id}\` | ${a.kind} | ${size} | ${a.animations.length?a.animations.join(', '):'—'} | ${a.pivotHints.length?a.pivotHints.slice(0,8).join(', '):'—'} |`);}lines.push('','## Authoring rule','','A GLB may suggest scale, nodes and animation bindings, but it never silently defines health, armor, footprint, collision, locomotion, faction, AI role or balance. Those remain explicit ForgeRTS data.','');
  await fs.writeFile(path.join(root,'ASSET_INGESTION_AUDIT.md'),lines.join('\n'));
  process.stdout.write(`Audited ${assets.length} assets\n`);
}
main().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
